Include <limits.h> for Linux musl libc
On Alpine 3.20 the standard C library is musl and compilation gives an
error:

~/code/nob.h $ clang -o nob nob.c
In file included from nob.c:3:
./nob.h:1176:43: error: use of undeclared identifier 'PATH_MAX'
 1176 |     char *buffer = (char*) nob_temp_alloc(PATH_MAX);
      |                                           ^
./nob.h:1177:24: error: use of undeclared identifier 'PATH_MAX'
 1177 |     if (getcwd(buffer, PATH_MAX) == NULL) {
      |                        ^
2 errors generated

I guess on Windows we get this header with <windows.h> even with
WIN32_LEAN_AND_MEAN.

On Debian it is somehow not required, I guess because of glibc.